# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Commitsense < Formula
  desc ""
  homepage "https://github.com/HRemonen/homebrew-commitsense"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/HRemonen/CommitSense/releases/download/v1.0.0/CommitSense_Darwin_x86_64.tar.gz"
      sha256 "de0f62f593d335170a6f8766971f34af498f4e2f046384b41bff2bdc37abd928"

      def install
        bin.install "CommitSense"
      end
    end
    on_arm do
      url "https://github.com/HRemonen/CommitSense/releases/download/v1.0.0/CommitSense_Darwin_arm64.tar.gz"
      sha256 "2ff20109502f627816d999d4372869938d8754949470d5ae29285a07df88fcb3"

      def install
        bin.install "CommitSense"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/HRemonen/CommitSense/releases/download/v1.0.0/CommitSense_Linux_x86_64.tar.gz"
        sha256 "3fdcfc01ba52db5e81c1b5301080bd5d73acef33ce42960cc27255da19814e9e"

        def install
          bin.install "CommitSense"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/HRemonen/CommitSense/releases/download/v1.0.0/CommitSense_Linux_arm64.tar.gz"
        sha256 "74c96ec4d29f04fd57acf4bb2fe4418654f5c971bd9c91ca647b2201f8ba51b4"

        def install
          bin.install "CommitSense"
        end
      end
    end
  end
end
